name: Docker Image CI

on: [push]

jobs:
  generate_build_id:
    runs-on: ubuntu-latest
    steps:
    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v2 
      with:
        token: ${{secrets.github_token}}

  check:
    needs: [generate_build_id]
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     - name: Run Node --check
       run: node --check index.js

  build:
    needs: [check]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build Latest Docker image
      run: docker build . --file Dockerfile --tag tscofield/discord-bot-clyde:latest
    - name: Build Versioned Docker image
      run: docker build . --file Dockerfile --tag tscofield/discord-bot-clyde:0.${{ steps.buildnumber.outputs.build_number }}
      
    - name: Login to docker hub
      run: echo ${{ secrets.DOCKERHUB_PASS }} | docker login --username tscofield --password-stdin
      
    - name: Push Latest to DockerHUB
      run: docker push tscofield/discord-bot-clyde:latest
    - name: Push Versioned to DockerHUB
      run: docker push tscofield/discord-bot-clyde:0.${{ steps.buildnumber.outputs.build_number }}



