name: Docker Image CI

on: [push]

jobs:
  check:
   runs-on: ubuntu-latest
   steps:
     - uses: action/checkout@v1
       name: Run Node --check
       run: node --check index.js

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag tscofield/discord-bot-clyde:latest
    
    - name: Login to docker hub
      run: echo ${{ secrets.DOCKERHUB_PASS }} | docker login --username tscofield --password-stdin
      
    - name: Push to DockerHUB
      run: docker push tscofield/discord-bot-clyde:latest

